controller_manager:
  ros__parameters:
    update_rate: 50
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    mecanum_controller:
      type: mecanum_drive_controller/MecanumDriveController

mecanum_controller:
  ros__parameters:
    front_left_wheel_names: ["front_left_wheel_joint"]
    front_right_wheel_names: ["front_right_wheel_joint"]
    back_left_wheel_names: ["rear_left_wheel_joint"]
    back_right_wheel_names: ["rear_right_wheel_joint"]
    
    wheel_separation_x: 0.4
    wheel_separation_y: 0.38
    wheel_radius: 0.05
    
    odom_frame_id: odom
    base_frame_id: base_link
